POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=1

###

PUT  http://localhost:3333/videos/58e2535c-6a50-44d7-a5b6-bbc08358085a
Content-Type: application/json

{
    "title": "video 2",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/ff45b060-a2e0-4452-b9e6-1d007a633b8b